// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bahlxnamxdbqpdwlndba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhaGx4bmFteGRicXBkd2xuZGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDUxMzIsImV4cCI6MjA1Mjk4MTEzMn0.E8JLMQ8KUVmc4W7NAgruyf5nBJRFyGqHpafhLjtl_VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);